# Using the lowest 5.x based version of PHP and related PHPUnit container from the Docker HUB
# Currently that's 5.6.20-fpm.
#
# Other supported versions can be found at https://hub.docker.com/r/wordpressdevelop/phpunit/tags
#
#
ENV VERSION '5.6.20-fpm'

FROM wordpressdevelop/phpunit:$VERSION
MAINTAINER Thomas Sjolshagen <thomas@eigthy20results.com>

