name: Release to wordpress.org

on:
  # Deploy when a new release is created
  release:
    # Only deploy when the admin creates/publishes/edits/pre-releases from GitHub
    types: [edited, published]

jobs:
  # To push the release (sources) to the WordPress.org SVN instance for this plugin
  wordpress:
    name: Push ${{ github.repository }} to wordpress.org (by ${{ github.actor }})
    runs-on: ubuntu-latest
    steps:
      - name: WordPress Plugin Deploy (by ${{ github.actor }})
      - uses: actions/checkout@v2
        with:
          repository: ${{ github.repository }}
          ref: main
      - name: Set the plugin SLUG name
        run: echo "SLUG=$(echo '${{ github.repository }}' | awk -F '/' '{print $1}')" >> $GITHUB_ENV
        shell: bash
      - name: WordPress Plugin Deploy for ${{ github.ref }} by ${{ github.actor }}
        uses: {{ github.repository }}@${{ github.ref }}
        env:
          SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
          SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
          GITHUB_TOKEN: ${{ secrets.GITHUB }}

