name: Test of "Release to wordpress.org" workflows

on:
  push:
    tags:
      - test_workflow*

jobs:
  # To push the release (sources) to the WordPress.org SVN instance for this plugin
  wordpress:
    name: Test of "Push to wordpress.org" workflow
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          repository: ${{ github.repository }}
          ref: test_workflow_updates
      - name: Set the plugin SLUG name
        run: echo "SLUG=$(echo '${{ github.repository }}' | awk -F '/' '{print $1}')" >> $GITHUB_ENV
        shell: bash
      - name: Test of "WordPress Plugin Deploy" for ${{ github.ref }} by ${{ github.actor }}
        uses: ${{ github.repository }}@test_workflow_updates
        env:
          SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
          SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
          GITHUB_TOKEN: ${{ secrets.GITHUB }}

